import { BigQuery } from "@google-cloud/bigquery";
import { Firestore } from "@google-cloud/firestore";
import type { Country, DataSource, InfrastructureIndicator, InvestmentIndicator, PopulationIndicator, Region, Report } from "@civicpulse/shared";

export interface ReportRepository { create(report: Report): Promise<Report>; getById(reportId: string): Promise<Report | null>; list(): Promise<Report[]>; }
export interface PopulationRepository { getByRegionId(regionId: string): Promise<PopulationIndicator | null>; }
export interface InfrastructureRepository { getByRegionId(regionId: string): Promise<InfrastructureIndicator[]>; }
export interface InvestmentRepository { getByRegionId(regionId: string): Promise<InvestmentIndicator[]>; }
export interface DataSourceRepository { getById(sourceId: string): Promise<DataSource | null>; list(): Promise<DataSource[]>; }
export interface RegionRepository { listByCountry(countryCode: string): Promise<Region[]>; }
export interface CountryRepository { list(): Promise<Country[]>; }
export interface RecommendationRecord { recommendationId: string; countryCode: string; regionId: string; category: string; priorityScore: number; generatedAt: string; }
export interface RecommendationRepository { create(recommendation: RecommendationRecord): Promise<RecommendationRecord>; getById(recommendationId: string): Promise<RecommendationRecord | null>; list(): Promise<RecommendationRecord[]>; }
export interface ApplicationRepositories { reports: ReportRepository; recommendations: RecommendationRepository; population: PopulationRepository; infrastructureRepo: InfrastructureRepository; investment: InvestmentRepository; dataSources: DataSourceRepository; regionsRepo: RegionRepository; countries: CountryRepository; }

export interface Lineage { sourceId: string; sourceName: string; publisher: string; dataYear: number; retrievedAt: string; license: string; sourceType: "synthetic_demo" | "public_dataset" | "citizen_live"; }
export const demoLineage: Lineage = { sourceId: "demo-in-indicators-2024", sourceName: "CivicPulse India demo indicators", publisher: "CivicPulse", dataYear: 2024, retrievedAt: "2024-12-01T00:00:00.000Z", license: "Synthetic demo data", sourceType: "synthetic_demo" };
export const brazilDemoLineage: Lineage = { sourceId: "demo-br-indicators-2024", sourceName: "CivicPulse Brazil prototype indicators", publisher: "CivicPulse", dataYear: 2024, retrievedAt: "2024-12-01T00:00:00.000Z", license: "Synthetic demo data", sourceType: "synthetic_demo" };
export const deterministicSeed = {
  populations: [{ regionId: "IN-DL-ND", population: 249998, populationDensity: 11320, vulnerabilityIndicator: 0.42, dataYear: 2024, sourceId: demoLineage.sourceId, sourceType: "synthetic_demo" }, { regionId: "IN-MH-PU", population: 330120, populationDensity: 5900, vulnerabilityIndicator: 0.37, dataYear: 2024, sourceId: demoLineage.sourceId, sourceType: "synthetic_demo" }, { regionId: "BR-SP-SP", population: 11451245, populationDensity: 7398, vulnerabilityIndicator: 0.38, dataYear: 2024, sourceId: brazilDemoLineage.sourceId, sourceType: "synthetic_demo" }, { regionId: "BR-PE-RE", population: 1488920, populationDensity: 2088, vulnerabilityIndicator: 0.46, dataYear: 2024, sourceId: brazilDemoLineage.sourceId, sourceType: "synthetic_demo" }] satisfies PopulationIndicator[],
  infrastructure: [{ regionId: "IN-DL-ND", category: "sanitation", infrastructureAdequacy: 0.48, infrastructureGap: 0.52, dataYear: 2024, sourceId: demoLineage.sourceId, sourceType: "synthetic_demo" }, { regionId: "IN-MH-PU", category: "water", infrastructureAdequacy: 0.61, infrastructureGap: 0.39, dataYear: 2024, sourceId: demoLineage.sourceId, sourceType: "synthetic_demo" }, { regionId: "BR-SP-SP", category: "transport", infrastructureAdequacy: 0.56, infrastructureGap: 0.44, dataYear: 2024, sourceId: brazilDemoLineage.sourceId, sourceType: "synthetic_demo" }, { regionId: "BR-PE-RE", category: "sanitation", infrastructureAdequacy: 0.43, infrastructureGap: 0.57, dataYear: 2024, sourceId: brazilDemoLineage.sourceId, sourceType: "synthetic_demo" }] satisfies InfrastructureIndicator[],
  investments: [{ regionId: "IN-DL-ND", category: "sanitation", plannedInvestmentIndex: 0.35, investmentGap: 0.65, dataYear: 2024, sourceId: demoLineage.sourceId, sourceType: "synthetic_demo" }, { regionId: "IN-MH-PU", category: "water", plannedInvestmentIndex: 0.58, investmentGap: 0.42, dataYear: 2024, sourceId: demoLineage.sourceId, sourceType: "synthetic_demo" }, { regionId: "BR-SP-SP", category: "transport", plannedInvestmentIndex: 0.51, investmentGap: 0.49, dataYear: 2024, sourceId: brazilDemoLineage.sourceId, sourceType: "synthetic_demo" }, { regionId: "BR-PE-RE", category: "sanitation", plannedInvestmentIndex: 0.31, investmentGap: 0.69, dataYear: 2024, sourceId: brazilDemoLineage.sourceId, sourceType: "synthetic_demo" }] satisfies InvestmentIndicator[],
  sources: [{ ...demoLineage, datasetUrl: "https://example.invalid/civicpulse/india-demo", notes: "Synthetic India prototype data; not government data." }, { ...brazilDemoLineage, datasetUrl: "https://example.invalid/civicpulse/brazil-demo", notes: "Synthetic Brazil prototype data; not official Brazilian data." }] satisfies DataSource[],
  regions: [{ regionId: "IN-DL-ND", countryCode: "IN", adminLevel: "district", name: "New Delhi", code: "ND", center: { latitude: 28.6139, longitude: 77.209 }, sourceType: "synthetic_demo" }, { regionId: "IN-MH-PU", countryCode: "IN", adminLevel: "district", name: "Pune", code: "PU", center: { latitude: 18.5204, longitude: 73.8567 }, sourceType: "synthetic_demo" }, { regionId: "BR-SP-SP", countryCode: "BR", adminLevel: "municipality", name: "São Paulo", code: "SP", center: { latitude: -23.5505, longitude: -46.6333 }, sourceType: "synthetic_demo" }, { regionId: "BR-PE-RE", countryCode: "BR", adminLevel: "municipality", name: "Recife", code: "RE", center: { latitude: -8.0476, longitude: -34.877 }, sourceType: "synthetic_demo" }] satisfies Region[],
  countries: [{ config: { countryCode: "IN", name: "India", languages: ["en", "hi"], administrativeLevels: ["state", "district"], defaultAdminLevel: "district", categories: ["water", "sanitation", "roads", "transport", "electricity", "education", "health", "housing", "public_safety", "digital_connectivity", "waste", "other"] }, enabled: true }, { config: { countryCode: "BR", name: "Brazil", languages: ["pt", "en"], administrativeLevels: ["state", "municipality"], defaultAdminLevel: "municipality", categories: ["water", "sanitation", "roads", "transport", "electricity", "education", "health", "housing", "public_safety", "digital_connectivity", "waste", "other"] }, enabled: true }] satisfies Country[],
};

export class InMemoryReportRepository implements ReportRepository { private readonly reports = new Map<string, Report>(); async create(report: Report) { this.reports.set(report.reportId, report); return report; } async getById(reportId: string) { return this.reports.get(reportId) ?? null; } async list() { return [...this.reports.values()]; } }
export class InMemoryRecommendationRepository implements RecommendationRepository { private readonly recommendations = new Map<string, RecommendationRecord>(); async create(recommendation: RecommendationRecord) { this.recommendations.set(recommendation.recommendationId, recommendation); return recommendation; } async getById(id: string) { return this.recommendations.get(id) ?? null; } async list() { return [...this.recommendations.values()]; } }
export class LocalSeedRepositories implements ApplicationRepositories {
  readonly reports = new InMemoryReportRepository();
  readonly recommendations = new InMemoryRecommendationRepository();
  readonly population: PopulationRepository = { getByRegionId: async (id) => deterministicSeed.populations.find((record) => record.regionId === id) ?? null };
  readonly infrastructureRepo: InfrastructureRepository = { getByRegionId: async (id) => deterministicSeed.infrastructure.filter((record) => record.regionId === id) };
  readonly investment: InvestmentRepository = { getByRegionId: async (id) => deterministicSeed.investments.filter((record) => record.regionId === id) };
  readonly dataSources: DataSourceRepository = { getById: async (id) => deterministicSeed.sources.find((source) => source.sourceId === id) ?? null, list: async () => [...deterministicSeed.sources] };
  readonly regionsRepo: RegionRepository = { listByCountry: async (code) => deterministicSeed.regions.filter((region) => region.countryCode === code) };
  readonly countries: CountryRepository = { list: async () => [...deterministicSeed.countries] };
}

export class FirestoreReportRepository implements ReportRepository {
  constructor(private readonly firestore: Firestore) {}
  async create(report: Report) { await this.firestore.collection("reports").doc(report.reportId).set(report); return report; }
  async getById(reportId: string) { const snapshot = await this.firestore.collection("reports").doc(reportId).get(); return snapshot.exists ? snapshot.data() as Report : null; }
  async list() { const snapshot = await this.firestore.collection("reports").get(); return snapshot.docs.map((doc) => doc.data() as Report); }
}
export class FirestoreRecommendationRepository implements RecommendationRepository {
  constructor(private readonly firestore: Firestore) {}
  async create(recommendation: RecommendationRecord) { await this.firestore.collection("recommendations").doc(recommendation.recommendationId).set(recommendation); return recommendation; }
  async getById(recommendationId: string) { const snapshot = await this.firestore.collection("recommendations").doc(recommendationId).get(); return snapshot.exists ? snapshot.data() as RecommendationRecord : null; }
  async list() { const snapshot = await this.firestore.collection("recommendations").get(); return snapshot.docs.map((doc) => doc.data() as RecommendationRecord); }
}
export class FirestoreCountryRepository implements CountryRepository { constructor(private readonly firestore: Firestore) {} async list() { const snapshot = await this.firestore.collection("countries").get(); return snapshot.docs.map((doc) => doc.data() as Country); } }

type QueryableBigQuery = Pick<BigQuery, "query">;
export class BigQueryAnalyticsRepositories {
  constructor(private readonly bigquery: QueryableBigQuery, private readonly dataset: string) {}
  private async rows(sql: string, params: Record<string, string>): Promise<Record<string, unknown>[]> { const [rows] = await this.bigquery.query({ query: sql, params, useLegacySql: false }); return rows as Record<string, unknown>[]; }
  private table(name: string) { return `\`${this.dataset}.${name}\``; }
  async populationForRegion(regionId: string): Promise<PopulationIndicator | null> { const row = (await this.rows(`SELECT region_id, population, population_density, vulnerability_indicator, data_year, source_id, source_type FROM ${this.table("population_indicators")} WHERE region_id=@regionId LIMIT 1`, { regionId }))[0]; return row ? { regionId: String(row.region_id), population: Number(row.population), populationDensity: row.population_density === null ? null : Number(row.population_density), vulnerabilityIndicator: row.vulnerability_indicator === null ? null : Number(row.vulnerability_indicator), dataYear: Number(row.data_year), sourceId: String(row.source_id), sourceType: row.source_type as PopulationIndicator["sourceType"] } : null; }
  async infrastructureForRegion(regionId: string): Promise<InfrastructureIndicator[]> { const rows = await this.rows(`SELECT region_id, category, infrastructure_adequacy, infrastructure_gap, data_year, source_id, source_type FROM ${this.table("infrastructure_indicators")} WHERE region_id=@regionId`, { regionId }); return rows.map((row) => ({ regionId: String(row.region_id), category: row.category as InfrastructureIndicator["category"], infrastructureAdequacy: Number(row.infrastructure_adequacy), infrastructureGap: Number(row.infrastructure_gap), dataYear: Number(row.data_year), sourceId: String(row.source_id), sourceType: row.source_type as InfrastructureIndicator["sourceType"] })); }
  async investmentForRegion(regionId: string): Promise<InvestmentIndicator[]> { const rows = await this.rows(`SELECT region_id, category, planned_investment_index, investment_gap, data_year, source_id, source_type FROM ${this.table("investment_indicators")} WHERE region_id=@regionId`, { regionId }); return rows.map((row) => ({ regionId: String(row.region_id), category: row.category as InvestmentIndicator["category"], plannedInvestmentIndex: Number(row.planned_investment_index), investmentGap: Number(row.investment_gap), dataYear: Number(row.data_year), sourceId: String(row.source_id), sourceType: row.source_type as InvestmentIndicator["sourceType"] })); }
  async sourceById(sourceId: string): Promise<DataSource | null> { return this.source((await this.rows(`SELECT * FROM ${this.table("data_sources")} WHERE source_id=@sourceId LIMIT 1`, { sourceId }))[0]); }
  async sources(): Promise<DataSource[]> { return (await this.rows(`SELECT * FROM ${this.table("data_sources")}`, {})).map((row) => this.source(row)).filter((value): value is DataSource => value !== null); }
  async regions(countryCode: string): Promise<Region[]> { const rows = await this.rows(`SELECT region_id, country_id, admin_level, region_name, region_code, latitude, longitude, source_type FROM ${this.table("admin_boundaries")} WHERE country_id=@countryCode`, { countryCode }); return rows.map((row) => ({ regionId: String(row.region_id), countryCode: row.country_id as Region["countryCode"], adminLevel: String(row.admin_level), name: String(row.region_name), code: String(row.region_code), center: row.latitude === null ? null : { latitude: Number(row.latitude), longitude: Number(row.longitude) }, sourceType: row.source_type as Region["sourceType"] })); }
  private source(row: Record<string, unknown> | undefined): DataSource | null { if (!row) return null; const timestamp = row.retrieved_at; const value = timestamp && typeof timestamp === "object" && "value" in timestamp ? (timestamp as { value: unknown }).value : timestamp; return { sourceId: String(row.source_id), sourceName: String(row.source_name), publisher: String(row.publisher), datasetUrl: String(row.dataset_url), retrievedAt: new Date(String(value)).toISOString(), dataYear: Number(row.data_year), license: String(row.license), sourceType: row.source_type as DataSource["sourceType"], notes: String(row.notes) }; }
}

export interface GcpConfig { projectId: string; location: string; firestoreDatabase: string; bigqueryDataset: string; }
export function gcpConfigFromEnv(env = process.env): GcpConfig { const projectId = env.GOOGLE_CLOUD_PROJECT; const location = env.GOOGLE_CLOUD_LOCATION; const firestoreDatabase = env.FIRESTORE_DATABASE; const bigqueryDataset = env.BIGQUERY_DATASET; if (!projectId || !location || !firestoreDatabase || !bigqueryDataset) throw new Error("GCP mode requires GOOGLE_CLOUD_PROJECT, GOOGLE_CLOUD_LOCATION, FIRESTORE_DATABASE, and BIGQUERY_DATASET"); return { projectId, location, firestoreDatabase, bigqueryDataset }; }
export function createRepositories(env = process.env): ApplicationRepositories {
  if ((env.REPOSITORY_MODE ?? "local") === "local") return new LocalSeedRepositories();
  if (env.REPOSITORY_MODE !== "gcp") throw new Error("REPOSITORY_MODE must be local or gcp");
  const config = gcpConfigFromEnv(env); const firestore = new Firestore({ projectId: config.projectId, databaseId: config.firestoreDatabase }); const analytics = new BigQueryAnalyticsRepositories(new BigQuery({ projectId: config.projectId, location: config.location }), `${config.projectId}.${config.bigqueryDataset}`);
  return { reports: new FirestoreReportRepository(firestore), recommendations: new FirestoreRecommendationRepository(firestore), countries: new FirestoreCountryRepository(firestore), population: { getByRegionId: (id) => analytics.populationForRegion(id) }, infrastructureRepo: { getByRegionId: (id) => analytics.infrastructureForRegion(id) }, investment: { getByRegionId: (id) => analytics.investmentForRegion(id) }, dataSources: { getById: (id) => analytics.sourceById(id), list: () => analytics.sources() }, regionsRepo: { listByCountry: (code) => analytics.regions(code) } };
}
